import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiHtml5,
  SiCss3,
  SiNodedotjs,
  SiReact,
  SiTypescript,
  SiLinux,
  SiArchlinux,
  SiCloudflare,
  SiObsidian,
  SiNotion,
  SiYoutube,
  SiAdobepremierepro,
  SiAutohotkey,
  SiFirebase,
  SiTailwindcss,
  SiVercel,
  SiGit,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaTwitter, FaInstagram, FaGlobe, FaProductHunt, FaYoutube, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  youtube: FaYoutube,
  producthunt: FaProductHunt,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  website: FaGlobe,
  twitter: FaXTwitter,
  instagram: FaInstagram,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  python: SiPython,
  html5: SiHtml5,
  css3: SiCss3,
  nodejs: SiNodedotjs,
  react: SiReact,
  typescript: SiTypescript,
  linux: SiLinux,
  archlinux: SiArchlinux,
  cloudflare: SiCloudflare,
  obsidian: SiObsidian,
  notion: SiNotion,
  youtubetech: SiYoutube,
  premierepro: SiAdobepremierepro,
  autohotkey: SiAutohotkey,
  firebase: SiFirebase,
  tailwindcss: SiTailwindcss,
  vercel: SiVercel,
  git: SiGit,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;